<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-android</TargetFramework>
        <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <!-- IMPORTANTE: Escolha um ID único. Uma vez publicado, não pode ser alterado. -->
        <ApplicationId>com.fabiodutram.browniansimpleapp</ApplicationId>
        <ApplicationVersion>1</ApplicationVersion>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationTitle>Brownian Simple App</ApplicationTitle>
        <AndroidPackageFormat>aab</AndroidPackageFormat> <!-- Alterado de apk para aab -->
    </PropertyGroup>    

    <!-- Propriedades de Assinatura para o modo Release -->
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <AndroidKeyStore>True</AndroidKeyStore>
        <AndroidSigningKeyAlias>$(AndroidSigningKeyAlias)</AndroidSigningKeyAlias>
        <AndroidSigningKeyPass>$(AndroidSigningKeyPass)</AndroidSigningKeyPass>
        <AndroidSigningStorePass>$(AndroidSigningStorePass)</AndroidSigningStorePass>
    </PropertyGroup>

    <ItemGroup>
        <AndroidResource Include="Icon.png">
            <Link>Resources\drawable\Icon.png</Link>
        </AndroidResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Android"/>
        <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SimpleBrownianF\SimpleBrownianF.csproj"/>
    </ItemGroup>
</Project>
